services:
  ias_app:
    container_name: ias_app
    build: .
    env_file: ./.env
    restart: unless-stopped
    entrypoint: sh ./docker-entrypoint.sh
    ports:
      - "8000"
    volumes:
      - /home/ias/boilerplate_ia/media:/app/media  # Monta o diretório de mídia
      - /home/ias/boilerplate_ia/static:/app/static  # Monta o diretório de estáticos (caso necessário)
    networks:
      - ias_network

  ias_nginx:
    image: nginx:latest
    container_name: ias_nginx
    restart: unless-stopped
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf  # Arquivo de configuração do Nginx
      - /home/ias/boilerplate_ia/media:/app/media  # Monta o diretório de mídia
      - /home/ias/boilerplate_ia/static:/app/static  # Monta o diretório de estáticos (caso necessário)
    depends_on:
      - ias_app
    ports:
      - "80:80"
    networks:
      - ias_network

networks:
  ias_network:
