volumes:
  postgres-data:

services:
  ias_db:
    image: postgres
    container_name: ias_db
    environment:
      POSTGRES_DB: db
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
    volumes:
      - postgres-data:/var/lib/postgresql/data
    ports:
      - "5432"
    restart: always
    networks:
      - ias_network

  ias_app:
    container_name: ias_app
    build: .
    env_file: ./.env
    restart: unless-stopped
    entrypoint: sh ./docker-entrypoint.sh
    ports:
      - "8000"
    volumes:
      - /home/ias/boilerplate_ia/media:/app/media
      - /home/ias/boilerplate_ia/static:/app/static
    networks:
      - ias_network

  ias_nginx:
    image: nginx:latest
    container_name: ias_nginx
    restart: unless-stopped
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./nginx/fullchain.pem:/etc/nginx/fullchain.pem
      - ./nginx/privkey.pem:/etc/nginx/privkey.pem
      - /home/ias/boilerplate_ia/media:/app/media
      - /home/ias/boilerplate_ia/static:/app/static
    depends_on:
      - ias_app
    ports:
      - "80:80"
      - "443:443"
    networks:
      - ias_network

networks:
  ias_network:
