# Generated by Django 5.1 on 2024-11-01 14:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('panel', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='panelmodel',
            name='image_airbag_icon_origin',
        ),
    ]
