# Generated by Django 4.2.15 on 2024-08-19 04:15

from django.db import migrations, models
import plate.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PlateModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('identifier', models.CharField(max_length=255)),
                ('product', models.CharField(max_length=255)),
                ('plate', models.CharField(max_length=255)),
                ('result', models.JSONField(blank=True, null=True)),
                ('labels_top', models.JSONField(blank=True, null=True)),
                ('labels_bottom', models.JSONField(blank=True, null=True)),
                ('img_top', models.ImageField(blank=True, null=True, upload_to=plate.models.upload_to_img_top)),
                ('img_bottom', models.ImageField(blank=True, null=True, upload_to=plate.models.upload_to_img_bottom)),
                ('match', models.BooleanField(default=False)),
                ('runtime', models.FloatField(default=0.0)),
                ('plate_image', models.ImageField(blank=True, null=True, upload_to=plate.models.upload_to_plate)),
            ],
        ),
    ]
