# Generated by Django 5.1 on 2024-10-30 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PlateModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('identifier', models.CharField(max_length=255)),
                ('type_vehicle', models.CharField(max_length=255)),
                ('angle', models.CharField(max_length=255)),
                ('product', models.CharField(max_length=255)),
                ('plate', models.CharField(max_length=255)),
                ('result', models.JSONField(blank=True, null=True)),
                ('labels_top', models.JSONField(blank=True, null=True)),
                ('labels_bottom', models.JSONField(blank=True, null=True)),
                ('match', models.BooleanField(default=False)),
                ('runtime', models.FloatField(default=0.0)),
            ],
        ),
    ]
