# Generated by Django 5.1 on 2024-09-06 20:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PlateModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('identifier', models.CharField(max_length=255)),
                ('type_vehicle', models.CharField(max_length=255)),
                ('angle', models.CharField(max_length=255)),
                ('product', models.CharField(max_length=255)),
                ('plate', models.CharField(max_length=255)),
                ('result', models.JSONField(blank=True, null=True)),
                ('labels_top', models.JSONField(blank=True, null=True)),
                ('labels_bottom', models.JSONField(blank=True, null=True)),
                ('plate_image', models.ImageField(max_length=255, upload_to='images/plates/complete')),
                ('img_top', models.ImageField(blank=True, max_length=255, null=True, upload_to='images/plates/top')),
                ('img_bottom', models.ImageField(blank=True, max_length=255, null=True, upload_to='images/plates/bottom')),
                ('match', models.BooleanField(default=False)),
                ('runtime', models.FloatField(default=0.0)),
            ],
        ),
    ]
